# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.23.1"

gem "tty-font", "~> 0.5.0"

gem "tty-table", "~> 0.12.0"

gem "yaml", "~> 0.1.1"
